package com.revature.get_comments;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.List;

    @Data
    @NoArgsConstructor
    @DynamoDBTable(tableName = "ForumNodes")
    public class Comment {

        @DynamoDBHashKey
        @DynamoDBAutoGeneratedKey
        private String id;

        @DynamoDBAttribute
        private String subject;

        @DynamoDBAttribute
        private List<String> ancestors;

        @DynamoDBIndexHashKey(attributeName = "parent", globalSecondaryIndexName = "parent-index")
        private String parent;

        @DynamoDBAttribute
        private String description;

        @DynamoDBAttribute
        private int childCount;

        @DynamoDBAttribute
        private String dateCreated;

        @DynamoDBAttribute
        private String owner;

        @DynamoDBAttribute
        private List<String> tags;

        public Comment(String id, String subject, String description, List<String> ancestors) {
            this.id = id;
            this.subject = subject;
            this.ancestors = ancestors;
            this.parent = ancestors.get(1);
            this.description = description;
            this.tags = null;
            this.childCount = 0;
            this.dateCreated = LocalDateTime.now().toString();
        }
}
